[font]
size=9

[selection]
save_to_clipboard=true

[cursor]
style = {
  shape = "Underline",
  blinking = "On"
}

[window]
opacity = 0.9
blur = true
decorations = "None"
dimensions = {
  columns = 120,
  lines = 24
}

[colors.primary]
background = "#0e1c24"
